[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 1
y = 2

[window]
opacity = 0.9

[window.padding]
x = 4
y = 4

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Delete"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[env]
TERM ="xterm-256color"
