"$schema" = 'https://starship.rs/config-schema.json'


format = """
[░▒▓](#a3aed2)\
[ 󰀵 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
$direnv\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$jobs\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
$fill\
$cmd_duration\
[ ](fg:#1d2230)\
$python\
[](fg:#212736 bg:#1d2230)\
$docker_context\
$kubernetes\
[](fg:#394260 bg:#212736)\
$aws\
$gcloud\
${custom.vpn}\
[](fg:#a3aed2 bg:#394260)\
$time\
[▓▒░](#a3aed2)\
\n$character"""


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[direnv]
disabled = false
symbol = "󰌪"
style = "fg:#e3e5e5 bg:#769ff0"
format = '[$symbol ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[jobs]
disabled = false
symbol = ""
format = '[ $symbol $number]($style)'
style = "bg:#212736"

[fill]
symbol = " "

[cmd_duration]
format = '[took $duration]($style)'

[python]
disabled = false
symbol = "󰌠"
style = "bg:#1d2230"
format = '[[ $symbol $pyenv_prefix($version) (\($virtualenv\) )](fg:#769ff0 bg:#1d2230)]($style)'

[docker_context]
disabled = true
symbol = "󰡨"
style = "bg:#212736"
format = '[[ $symbol $context ](fg:#769ff0 bg:#212736)]($style)'

[kubernetes]
disabled = true
symbol = "󱃾"
style = "bg:#212736"
format = '[[ $symbol $context( \($namespace\)) ](fg:#769ff0 bg:#212736)]($style)'

[aws]
disabled = false
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $profile ]($style)'

[gcloud]
disabled = true
symbol = "󱇶"
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $project ]($style)'

[time]
disabled = false
time_format = "%T"
style = "fg:#090c0c bg:#a3aed2"
format = '[ $time  ]($style)'

[custom.vpn]
disabled = true
command = "~/Projects/src/github.com/satoshiyamamoto/starship-vpn/starship-vpn.sh prompt"
when = "~/Projects/src/github.com/satoshiyamamoto/starship-vpn/starship-vpn.sh connected"
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $output ](fg:#769ff0 bg:#394260)]($style)'
ignore_timeout = true
