"$schema" = 'https://starship.rs/config-schema.json'


format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
${env_var.ZMX_SESSION}\
$hostname\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
$direnv\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$jobs\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
\n$character"""


[hostname]
style = "bg:#a3aed2 fg:#090c0c"
format = '[$hostname]($style)'
trim_at = ".local"
ssh_only = true

[env_var.ZMX_SESSION]
symbol = " "
format = "[ $symbol$env_value ]($style)"
description = "zmx session name"
style = "bg:#a3aed2 fg:#090c0c"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[direnv]
disabled = false
symbol = "󰌪"
style = "fg:#e3e5e5 bg:#769ff0"
format = '[$symbol ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[jobs]
disabled = false
symbol = ""
format = '[ $symbol $number]($style)'
style = "bg:#212736"
