" Entry point: source role-based config from rc/ in dependency order.
let mapleader = ' '

runtime rc/options.vim
runtime rc/plugin-settings.vim
runtime rc/plugins.vim
runtime rc/mappings.vim
runtime rc/completion.vim
runtime rc/lsp.vim
runtime rc/format.vim
runtime rc/terminal.vim
runtime rc/colors.vim
