set mouse=a
set number
set relativenumber
set splitbelow
set splitright
set incsearch
set hlsearch
set confirm
set updatetime=100
set timeoutlen=300
set ttimeoutlen=10
set nocompatible
set grepprg=rg\ --vimgrep\ --hidden\ --glob\ '!.git'
set grepformat=%f:%l:%c:%m
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set t_ut=
set t_RB=
set background=dark

if !1 | finish | endif
let mapleader = ' '

" Mappings
"" Windows
nnoremap <C-J>              <C-W>j
nnoremap <C-K>              <C-W>k
nnoremap <C-H>              <C-W>h
nnoremap <C-L>              <C-W>l
tnoremap <Esc>              <C-W>N
tnoremap <C-[>              <C-W>N
nnoremap <silent><C-/>      :bo terminal ++close ++rows=12<CR>
"" Buffers
nnoremap <silent><Esc>      :noh<CR>
nnoremap <silent><C-[>      :noh<CR>
nnoremap <silent><Leader>bd :bprevious<Bar>bdelete #<CR>
nnoremap <silent><Leader>bo :%bdelete<Bar>edit #<Bar>bdelete #<CR>
nnoremap <silent>[c         <Plug>(GitGutterPrevHunk)<CR>
nnoremap <silent>]c         <Plug>(GitGutterNextHunk)<CR>
nmap     <silent>s          <Plug>(easymotion-s2)
nmap     <silent>S          <Plug>(easymotion-bd-w)
"" Pickers
nnoremap <silent><C-P>      :Files<CR>
nmap     <Leader><Leader>   <C-P>
nnoremap <silent><Leader>/  :Rg<CR>
nnoremap <silent><Leader>,  :Buffers<CR>
nnoremap <silent><Leader>e  :NERDTreeToggle<CR>
nnoremap <silent><Leader>r  :NERDTreeRefreshRoot<CR>
nnoremap <silent><Leader>n  :NERDTreeFind<CR>
"" Completions
imap <expr><C-J> vsnip#expandable() ? '<Plug>(vsnip-expand)'         : '<C-J>'
smap <expr><C-J> vsnip#expandable() ? '<Plug>(vsnip-expand)'         : '<C-J>'
imap <expr><C-L> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<C-L>'
smap <expr><C-L> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<C-L>'
"" IME
inoremap <C-S-J>            <Nop>
inoremap <C-S-;>            <Nop>

let g:terminal_ansi_colors = [
    \ '#15161e', '#f7768e', '#9ece6a', '#e0af68',
    \ '#7aa2f7', '#bb9af7', '#7dcfff', '#a9b1d6',
    \ '#414868', '#f7768e', '#9ece6a', '#e0af68',
    \ '#7aa2f7', '#bb9af7', '#7dcfff', '#c0caf5',
    \ ]
let g:airline_theme='tokyonight_night'
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:rainbow_active = 1
let g:rainbow_conf = { 'separately': { 'nerdtree': 0 } }
let g:EasyMotion_do_mapping = 0
let g:NERDTreeCascadeOpenSingleChildDir = 1

" Plugins
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin()
" language server & completion
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'mattn/vim-lsp-settings'
Plug 'lighttiger2505/sqls.vim'
" snippet
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'rafamadriz/friendly-snippets'
Plug 'mattn/vim-goimports'
Plug 'mattn/emmet-vim'
Plug 'jiangmiao/auto-pairs'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'
" formatter
Plug 'editorconfig/editorconfig-vim'
Plug 'prettier/vim-prettier', {
    \ 'do': 'yarn install --frozen-lockfile --production',
    \ 'for': ['javascript', 'typescript', 'css', 'json',
    \         'markdown', 'vue', 'yaml', 'html'] }
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
Plug 'google/vim-glaive'
" finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
" theme
Plug 'folke/tokyonight.nvim'
Plug 'satoshiyamamoto/vim-github-dark'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'luochen1990/rainbow'
call plug#end()

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
    \| PlugInstall --sync | source $MYVIMRC
    \| endif

function! s:OnLspBufferEnabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <buffer> gO <Plug>(lsp-document-symbol-search)
  nmap <buffer> grr <Plug>(lsp-references)
  nmap <buffer> gri <Plug>(lsp-implementation)
  nmap <buffer> grn <Plug>(lsp-rename)
  nmap <buffer> gra <Plug>(lsp-code-action)
  nmap <buffer> [d <Plug>(lsp-previous-diagnostic)
  nmap <buffer> ]d <Plug>(lsp-next-diagnostic)
  nmap <buffer> K <Plug>(lsp-hover)
  nmap <buffer> <Leader>f <Plug>(lsp-document-format)
  inoremap <buffer> <expr><C-F> lsp#scroll(+4)
  inoremap <buffer> <expr><C-D> lsp#scroll(-4)

  " let g:lsp_format_sync_timeout = 1000
  " autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
endfunction

augroup lsp_install
  autocmd!
  autocmd User lsp_buffer_enabled call s:OnLspBufferEnabled()
augroup END

augroup asyncomplete_sources
  autocmd!
  autocmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#buffer#get_source_options({
      \   'name': 'buffer',
      \   'allowlist': ['*'],
      \   'priority': 15,
      \   'completor': function('asyncomplete#sources#buffer#completor'),
      \   'config': { 'max_buffer_size': 1000000 },
      \ }))
  autocmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#file#get_source_options({
      \   'name': 'file',
      \   'allowlist': ['*'],
      \   'priority': 10,
      \   'completor': function('asyncomplete#sources#file#completor'),
      \ }))
augroup END

augroup filetype_settings
  autocmd!
  autocmd FileType tf set filetype=terraform
augroup END

augroup autoformat_settings
  autocmd!
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,arduino AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType javascript,html,css,sass,scss,less,json
      \ AutoFormatBuffer prettier
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer black
  autocmd FileType rust AutoFormatBuffer rustfmt
augroup END

augroup terminal_settings
  autocmd!
  autocmd TerminalWinOpen * setlocal nonumber norelativenumber
augroup END

function! s:TransparentHighlights() abort
  highlight Normal       ctermbg=NONE guibg=NONE
  highlight SignColumn   ctermbg=NONE guibg=NONE
  highlight LineNr       ctermbg=NONE guibg=NONE
  highlight CursorLineNr ctermbg=NONE guibg=NONE
  highlight FoldColumn   ctermbg=NONE guibg=NONE
endfunction

augroup transparency
  autocmd!
  autocmd ColorScheme * call s:TransparentHighlights()
augroup END

set rtp+=~/.vim/plugged/tokyonight.nvim/extras/vim
colorscheme tokyonight-night
