onboarding = false

[theme]
name = "tokyo-night"
auto_switch = false

[keys]
switch_tab = "prefix+1..9"
switch_workspace = "prefix+shift+1..9"
focus_agent = "prefix+alt+1..9"

[ui]
prompt_new_tab_name = true
pane_borders = true
pane_gaps = true
agent_panel_sort = "priority"
tab_bar_right = [
  { type = "zoom" },
  { type = "hostname" },
  { type = "datetime", format = "%H:%M" },
  # { type = "text", text = "prod" },
  # { type = "command", command = "~/.config/herdr/status.sh", interval_seconds = 5, timeout_seconds = 2 },
]
tab_bar_right_separator = " · "

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"

[experimental]
switch_ascii_input_source_in_prefix = true
kitty_graphics = true
