#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source PATH environment settings.
export DOTDIR="${HOME}/Develop/src/github.com/satoshiyamamoto/dotfiles"
if [[ -s "${DOTDIR}/env" ]]; then
  source "${DOTDIR}/env"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${DOTDIR}/aliases.mac" ]]; then
  source "${DOTDIR}/aliases.mac"
fi

if [[ -s "${DOTDIR}/functions" ]]; then
  source "${DOTDIR}/functions"
fi
